src/Entity/Transaction.php
<?php

namespace App\Entity;

use App\Repository\TransactionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TransactionRepository::class)]
class Transaction
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $quantity = null;

    #[ORM\Column]
    private ?bool $is_in = null;

    #[ORM\Column(nullable: true)]
    private ?int $vat = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $unit_price = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $transaction_date = null;

    #[ORM\ManyToOne(inversedBy: 'transactions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'transactions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Warehouse $warehouse = null;

    #[ORM\ManyToOne(inversedBy: 'transactions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Article $article = null;

    #[ORM\OneToMany(targetEntity: Invoice::class, mappedBy: 'transaction')]
    private Collection $invoices;

    public function __construct()
    {
        $this->invoices = new ArrayCollection();
        if ($this->transaction_date === null) {
            $this->transaction_date = new \DateTime();
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): static
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function isIsIn(): ?bool
    {
        return $this->is_in;
    }

    public function setIsIn(bool $is_in): static
    {
        $this->is_in = $is_in;

        return $this;
    }

    public function getVat(): ?int
    {
        return $this->vat;
    }

    public function setVat(?int $vat): static
    {
        $this->vat = $vat;

        return $this;
    }

    public function getUnitPrice(): ?string
    {
        return $this->unit_price;
    }

    public function setUnitPrice(?string $unit_price): static
    {
        $this->unit_price = $unit_price;

        return $this;
    }

    public function getTransactionDate(): ?\DateTimeInterface
    {
        return $this->transaction_date;
    }

    public function setTransactionDate(?\DateTimeInterface $transaction_date): static
{
    $this->transaction_date = $transaction_date;

    return $this;
}

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getWarehouse(): ?Warehouse
    {
        return $this->warehouse;
    }

    public function setWarehouse(?Warehouse $warehouse): static
    {
        $this->warehouse = $warehouse;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): static
    {
        $this->article = $article;

        return $this;
    }

    /**
     * @return Collection<int, Invoice>
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): static
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices->add($invoice);
            $invoice->setTransaction($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): static
    {
        if ($this->invoices->removeElement($invoice)) {
            // set the owning side to null (unless already changed)
            if ($invoice->getTransaction() === $this) {
                $invoice->setTransaction(null);
            }
        }

        return $this;
    }
}

src/Form/TransactionType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Transaction;
use App\Entity\Warehouse;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TransactionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('warehouse', EntityType::class, [
                'class' => Warehouse::class,
                'choice_label' => 'name',
            ])
            ->add('article', EntityType::class, [
                'class' => Article::class,
                'choice_label' => 'name',
            ])
            ->add('quantity');
            if ($options['is_in']) {
                $builder->add('vat')
                        ->add('unit_price');
            }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Transaction::class,
            'is_in' => true, // Default value, adjust as necessary
        ]);
    }
}

src/Controller/TransactionController.php
<?php

namespace App\Controller;

use App\Entity\Transaction;
use App\Form\TransactionType;
use App\Repository\TransactionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/transaction')]
class TransactionController extends AbstractController
{
    #[Route('/', name: 'app_transaction_index', methods: ['GET'])]
    public function index(TransactionRepository $transactionRepository): Response
    {
        return $this->render('transaction/index.html.twig', [
            'transactions' => $transactionRepository->findAll(),
        ]);
    }

    #[Route('/new/in', name: 'app_transaction_new_in', methods: ['GET', 'POST'])]
    public function newIn(Request $request, EntityManagerInterface $entityManager): Response
    {
        return $this -> new($request, $entityManager, true);
    }

    #[Route('/new/out', name: 'app_transaction_new_out', methods: ['GET', 'POST'])]
    public function newOut(Request $request, EntityManagerInterface $entityManager): Response
    {
        return $this -> new($request, $entityManager, false);
    }

    #[Route('/new', name: 'app_transaction_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, bool $is_in): Response
    {
        $transaction = new Transaction();
        $transaction->setIsIn($is_in);
        $form = $this->createForm(TransactionType::class, $transaction, [
            'is_in' => $is_in,
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Set the user to the currently logged-in user
            $transaction->setUser($this->getUser());

            $entityManager->persist($transaction);
            $entityManager->flush();

            return $this->redirectToRoute('app_transaction_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('transaction/new.html.twig', [
            'transaction' => $transaction,
            'form' => $form,
            'transactionType'=> $is_in ? 'Incoming' : 'Outgoing',
        ]);
    }

    #[Route('/{id}', name: 'app_transaction_show', methods: ['GET'])]
    public function show(Transaction $transaction): Response
    {
        return $this->render('transaction/show.html.twig', [
            'transaction' => $transaction,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_transaction_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Transaction $transaction, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TransactionType::class, $transaction);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_transaction_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('transaction/edit.html.twig', [
            'transaction' => $transaction,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_transaction_delete', methods: ['POST'])]
    public function delete(Request $request, Transaction $transaction, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $transaction->getId(), $request->request->get('_token'))) {
            $entityManager->remove($transaction);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_transaction_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/transaction/_delete_form.html.twig
<form method="post" action="{{ path('app_transaction_delete', {'id': transaction.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ transaction.id) }}">
    <button class="btn">Delete</button>
</form>

templates/transaction/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/transaction/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Transaction{% endblock %}

{% block body %}
    <h1>Edit Transaction</h1>

    {{ include('transaction/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_transaction_index') }}">back to list</a>

    {{ include('transaction/_delete_form.html.twig') }}
{% endblock %}

templates/transaction/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Transaction index{% endblock %}

{% block body %}
    <h1>Transaction index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Type</th>
                <th>Article</th>
                <th>Quantity</th>
                <th>Vat</th>
                <th>Price_per_unit</th>
                <th>Transaction_Date</th>
                <th>User</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for transaction in transactions %}
            <tr>
                <td>{{ transaction.isIn ? 'In' : 'Out' }}</td>
                <td>{{ transaction.article.name}}</td>
                <td>{{ transaction.quantity }}</td>
                <td>{{ transaction.vat }}</td>
                <td>{{ transaction.unitPrice }}</td>
                <td>{{ transaction.transactionDate ? transaction.transactionDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ transaction.user.username }}</td>
                <td>
                    <a href="{{ path('app_transaction_show', {'id': transaction.id}) }}">show</a>
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('app_transaction_edit', {'id': transaction.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <a href="{{ path('app_transaction_new') }}">Create new</a> #}
    <a href="{{ path('app_transaction_new_in') }}">Create new in</a>
    <a href="{{ path('app_transaction_new_out') }}">Create new out</a>
{% endblock %}

templates/transaction/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New {{transactionType}} Transaction{% endblock %}

{% block body %}
    <h1>Create new {{transactionType}} Transaction</h1>

    {{ include('transaction/_form.html.twig') }}

    <a href="{{ path('app_transaction_index') }}">back to list</a>
{% endblock %}

templates/transaction/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Transaction{% endblock %}

{% block body %}
    <h1>Transaction</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Type</th>
                <td>{{ transaction.isIn ? 'In' : 'Out' }}</td>
            </tr>
            <tr>
                <th>Article</th>
                <td>{{ transaction.article.name }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ transaction.quantity }}</td>
            </tr>
            
            <tr>
                <th>Vat</th>
                <td>{{ transaction.vat }}</td>
            </tr>
            <tr>
                <th>Price_per_unit</th>
                <td>{{ transaction.unitPrice }}</td>
            </tr>
            <tr>
                <th>Transaction_Date</th>
                <td>{{ transaction.transactionDate ? transaction.transactionDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>User</th>
                <td>{{ transaction.user.username }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_transaction_index') }}">back to list</a>
    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('app_transaction_edit', {'id': transaction.id}) }}">edit</a>
    
    {{ include('transaction/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}